import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

export async function createReportPdf(analysis) {
  const {
    filename = 'resume',
    score = 0,
    summary = '',
    strengths = [],
    weaknesses = [],
    missingSkills = [],
    suggestions = []
  } = analysis;

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const bufferChunks = [];
  const output = new PassThrough();

  doc.pipe(output);
  output.on('data', chunk => bufferChunks.push(chunk));

  doc.fontSize(20).fillColor('#111827').text('AI Resume Audit Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor('#6b7280').text(`File: ${filename}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });

  doc.moveDown(1.2);
  doc.fillColor('#111827');
  doc.fontSize(16).text(`ATS Score: ${score} / 100`, { continued: true });
  doc.fontSize(12).fillColor('#4b5563').text('  •  Report based on content analysis and resume alignment', { continued: false });
  doc.moveDown(0.8);

  doc.fontSize(14).fillColor('#111827').text('Summary', { underline: true });
  doc.moveDown(0.25);
  doc.fontSize(11).fillColor('#374151').text(summary, { lineGap: 4 });
  doc.moveDown(0.8);

  const renderSection = (title, items, fallback) => {
    doc.fontSize(14).fillColor('#111827').text(title, { underline: true });
    doc.moveDown(0.25);
    if (items.length === 0) {
      doc.fontSize(11).fillColor('#6b7280').text(fallback, { lineGap: 4 });
      doc.moveDown(0.75);
      return;
    }
    items.forEach((item, index) => {
      doc.fontSize(11).fillColor('#111827').text(`${index + 1}. ${item}`, {
        paragraphGap: 4,
        lineGap: 4,
      });
      doc.moveDown(0.25);
    });
    doc.moveDown(0.6);
  };

  renderSection('Strengths', strengths, 'No positive highlights were detected in this analysis.');
  renderSection('What to Fix', weaknesses, 'No critical issues were detected. Consider fine-tuning formatting and impact statements.');
  renderSection('What is Missing', missingSkills, 'No obvious missing sections or skill categories were detected.');
  renderSection('Improvement Suggestions', suggestions, 'No specific recommendations were detected at this time.');

  doc.moveDown(1);
  doc.fontSize(10).fillColor('#6b7280').text('Report generated by AI Resume Analyzer. Review the findings and update your resume with measurable achievements, clear headings, and relevant skills.', {
    align: 'left',
    lineGap: 4,
  });

  doc.end();

  return new Promise((resolve, reject) => {
    output.on('end', () => resolve(Buffer.concat(bufferChunks)));
    output.on('error', reject);
    doc.on('error', reject);
  });
}
