import React, { useEffect, useState } from 'react';
import { 
  Sparkles, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  ArrowLeft, 
  Download, 
  Copy, 
  Check,
  FileText,
  HelpCircle,
  Lightbulb,
  Target,
  TrendingUp
} from 'lucide-react';

export default function Dashboard({ result, onReset }) {
  const { 
    score, 
    summary, 
    strengths = [], 
    weaknesses = [], 
    missingSkills = [], 
    suggestions = [], 
    filename,
    isMock 
  } = result;

  const [dashOffset, setDashOffset] = useState(351.8);
  const [copied, setCopied] = useState(false);
  const [animatedScore, setAnimatedScore] = useState(0);

  // Animate score number counting up
  useEffect(() => {
    let frame;
    let start = 0;
    const duration = 1200;
    const startTime = performance.now();

    const animate = (currentTime) => {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      // ease-out curve
      const eased = 1 - Math.pow(1 - progress, 3);
      setAnimatedScore(Math.round(eased * score));
      if (progress < 1) {
        frame = requestAnimationFrame(animate);
      }
    };
    frame = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(frame);
  }, [score]);

  // Animate gauge stroke
  useEffect(() => {
    const circumference = 2 * Math.PI * 56; // 351.8
    const timer = setTimeout(() => {
      setDashOffset(circumference - (circumference * score) / 100);
    }, 100);
    return () => clearTimeout(timer);
  }, [score]);

  const getScoreClassification = (num) => {
    if (num >= 85) return { text: 'Excellent Match', badge: 'excellent', colorClass: 'score-excellent' };
    if (num >= 70) return { text: 'Good Match', badge: 'good', colorClass: 'score-good' };
    return { text: 'Needs Optimization', badge: 'needs-work', colorClass: 'score-needs-work' };
  };

  const classification = getScoreClassification(score);

  const handleCopyReport = async () => {
    const reportText = `# AI Resume Audit — ${filename}
**ATS Score:** ${score}/100 — ${classification.text}

## Summary
${summary}

## What's Working Well
${strengths.map(s => `✅ ${s}`).join('\n')}

## What to Fix
${weaknesses.map(w => `❌ ${w}`).join('\n')}

## What's Missing
${missingSkills.map(m => `⚠️ ${m}`).join('\n')}

## How to Improve
${suggestions.map(s => `💡 ${s}`).join('\n')}
---
Generated by AI Resume Analyzer`;

    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-audit-${filename.replace(/\.[^/.]+$/, "")}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    try {
      const response = await fetch('/api/report-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(result),
      });

      if (!response.ok) {
        const errorBody = await response.json().catch(() => null);
        throw new Error(errorBody?.error || 'Failed to generate PDF report.');
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `resume-audit-${filename.replace(/\.[^/.]+$/, "")}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF download failed:', err);
      alert(err.message || 'Unable to download PDF report.');
    }
  };

  // Total actionable items count
  const totalActions = weaknesses.length + missingSkills.length + suggestions.length;

  return (
    <div className="dashboard-grid">
      
      {/* ─── Sidebar ─── */}
      <div className="sidebar-panel">

        <div className="glass-card score-card">
          <div className="gauge-wrapper">
            <svg width="140" height="140" className="gauge-svg">
              <circle cx="70" cy="70" r="56" className="gauge-bg" />
              <circle 
                cx="70" cy="70" r="56"
                className={`gauge-fill ${classification.colorClass}`}
                strokeDasharray="351.8"
                strokeDashoffset={dashOffset}
              />
            </svg>
            <div className="gauge-text">
              <span className="gauge-number">{animatedScore}</span>
              <span className="gauge-label">ATS Score</span>
            </div>
          </div>
          <h4 className="score-title">{classification.text}</h4>
          <span className={`score-badge ${classification.badge}`}>{score} / 100</span>
          <div className="file-badge">
            <FileText size={14} />
            <span title={filename}>{filename}</span>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="glass-card" style={{ padding: '1.25rem' }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.75rem' }}>Quick Stats</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
            <div className="stat-row">
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--color-success)' }}><CheckCircle2 size={14} /> Strengths</span>
              <span className="stat-count">{strengths.length}</span>
            </div>
            <div className="stat-row">
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--color-danger)' }}><XCircle size={14} /> Issues</span>
              <span className="stat-count">{weaknesses.length}</span>
            </div>
            <div className="stat-row">
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--color-warning)' }}><AlertTriangle size={14} /> Missing</span>
              <span className="stat-count">{missingSkills.length}</span>
            </div>
            <div className="stat-row">
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--color-info)' }}><Lightbulb size={14} /> Tips</span>
              <span className="stat-count">{suggestions.length}</span>
            </div>
          </div>
        </div>

        {isMock && (
          <div className="mock-banner">
            <HelpCircle size={16} />
            <div>
              <p style={{ fontWeight: '500', marginBottom: '2px' }}>Mock Mode</p>
              <p style={{ fontSize: '0.75rem', opacity: 0.75 }}>
                Add your API key in <code>.env</code> for real AI analysis.
              </p>
            </div>
          </div>
        )}

        <button onClick={onReset} className="btn-secondary" style={{ width: '100%', justifyContent: 'center' }}>
          <ArrowLeft size={16} /> Upload Another
        </button>
      </div>

      {/* ─── Main Content: All Sections Visible ─── */}
      <div className="results-panel">
        
        {/* Action Bar */}
        <div className="results-header-actions">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Target size={18} style={{ color: 'var(--text-muted)' }} />
            <span style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
              <strong style={{ color: 'var(--text-primary)' }}>{totalActions}</strong> actionable items found
            </span>
          </div>
          <div className="action-buttons">
            <button onClick={handleCopyReport} className="btn-icon" title={copied ? 'Copied!' : 'Copy full report'}>
              {copied ? <Check size={16} style={{ color: 'var(--color-success)' }} /> : <Copy size={16} />}
            </button>
            <button onClick={handleDownloadJson} className="btn-icon" title="Download JSON">
              <Download size={16} />
            </button>
            <button onClick={handleDownloadPdf} className="btn-icon" title="Download PDF report">
              <FileText size={16} />
            </button>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="glass-card section-card">
          <h3 className="section-header">
            <Sparkles size={18} style={{ color: 'var(--border-focus)' }} /> Executive Summary
          </h3>
          <p className="text-summary">{summary}</p>
        </div>

        {/* What's Working — Strengths */}
        <div className="glass-card section-card">
          <h3 className="section-header">
            <CheckCircle2 size={18} style={{ color: 'var(--color-success)' }} /> What's Working Well
          </h3>
          <ul className="bullet-list">
            {strengths.map((str, idx) => (
              <li key={idx} className="bullet-item strength">
                <CheckCircle2 size={16} />
                <span>{str}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* What to Fix — Weaknesses */}
        {weaknesses.length > 0 && (
          <div className="glass-card section-card section-danger">
            <h3 className="section-header">
              <XCircle size={18} style={{ color: 'var(--color-danger)' }} /> What to Fix
            </h3>
            <ul className="bullet-list">
              {weaknesses.map((weak, idx) => (
                <li key={idx} className="bullet-item weakness">
                  <XCircle size={16} />
                  <span>{weak}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* What's Missing — Skills & Sections */}
        {missingSkills.length > 0 && (
          <div className="glass-card section-card section-warning">
            <h3 className="section-header">
              <AlertTriangle size={18} style={{ color: 'var(--color-warning)' }} /> What's Missing
            </h3>
            <ul className="bullet-list">
              {missingSkills.map((miss, idx) => (
                <li key={idx} className="bullet-item missing">
                  <AlertTriangle size={16} />
                  <span>{miss}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* How to Improve — Suggestions */}
        {suggestions.length > 0 && (
          <div className="glass-card section-card section-info">
            <h3 className="section-header">
              <TrendingUp size={18} style={{ color: 'var(--color-info)' }} /> How to Improve
            </h3>
            <ul className="bullet-list">
              {suggestions.map((sug, idx) => (
                <li key={idx} className="bullet-item suggestion">
                  <Lightbulb size={16} />
                  <span>{sug}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

      </div>
    </div>
  );
}
